### ISSUE TITLE
getInfo() vs C_GetSessionInfo()

### ISSUE THREAD

**Issue by vjardin** [gamringer/php-pkcs11#11]
I do not understand this call of getInfo() for the C_GetSessionInfo() method:
https://github.com/gamringer/php-pkcs11/blob/444426cbc39d2594fba01f44bd8ece428d22bfda/pkcs11module.c#L741

please, what is the intend ?

**Comment by gamringer** [comment]
It's callin getInfo() on the Pkcs11\Session object. which in turns calls C_GetSessionInfo

See pkcs11session.c:88

**Comment by vjardin** [comment]
Thanks I got the point
 I made some confusions between de Module's getInfo () and the Session's getInfo(). I guess it was a bit late.
