### ISSUE TITLE
[placeholder] minutes of Guillaume/Vincent's chat

### ISSUE THREAD

**Issue by vjardin** [gamringer/php-pkcs11#17]
Tonight, Guillaume and I had a sync up call (in French :D) in order to target the v1 of this PHP extension:

- finalize the support of C_ Oasis like method: Guillaume can handle some 'write/set' operations while I cannot
- be able to run "make test" without any HW PKCS11: let's use https://github.com/opendnssec/SoftHSMv2, but we need a how to ?
The integration with Travis would be done after the v1
- remove the usage of `call_obj_func()` in order to use the models of php_C_xyz() calls so we can get the proper return'd values.
- keep the current design using some 'factory::' methods that leverages `object_init_ex()` instead of using a traditional new/constructor approach. However, it leads to some limitations in order to extend these PHP classes. Moreover, some PHP developers may look for the 'traditional' constructors somehow. We'll postpone the support of vanilla constructor (and maybe destructor) after a v1
- Get the support of C_WaitForSlotEvent(): tough one but it shall prevent the usage of Winscard that would be overkilled (https://pcsclite.apdu.fr/api/winscard_8h_source.html or https://docs.microsoft.com/en-us/windows/win32/api/winscard/)
- some references about PHP testing: https://qa.php.net/phpt_details.php and https://qa.php.net/expectf_details.php

**Comment by gamringer** [comment]
I opened #23 & #24. The rest is completed.
