### ISSUE TITLE
Build broken with PHP < 7.4

### ISSUE THREAD

**Issue by remicollet** [gamringer/php-pkcs11#20]
package.xml states minimal supported version is 7.0.0

But build fails with PHP < 7.4

`/builddir/build/BUILD/php-pecl-pkcs11-0.1/NTS/pkcs11object.c:57:54: error: 'ZEND_THIS' undeclared (first use in this function); did you mean 'ZEND_TLS'?`

**Comment by gamringer** [comment]
I changed certain things since it was indeed compatible with <7.4. I changed the minimum supported version to 7.4, since that's what currently supported by PHP anyway.
