### ISSUE TITLE
Support C_WaitForSlotEvent()

### ISSUE THREAD

**Issue by gamringer** [gamringer/php-pkcs11#24]
As discussed in #17 

Support `C_WaitForSlotEvent()`

Details TBD

**Comment by vjardin** [comment]
Placeholder:
   https://github.com/opendnssec/SoftHSMv2/blob/20a53bd083a6134ce2230f80edda5dc8be0366bd/src/lib/SoftHSM.cpp#L7234

We should assume that a limited support is available from SoftHSM2 unless someone shows up some dynamics in order to get an emulated event.

**Comment by vjardin** [comment]
WIP: https://github.com/gamringer/php-pkcs11/pull/34

**Comment by vjardin** [comment]
Why closed ?

**Comment by vjardin** [comment]
Got it, thanks for your updates: 
  https://github.com/gamringer/php-pkcs11/commit/107fede0961a9a4d4aa9f8ff88cde5b958326287#diff-d296f41411d8360e6ac30808dbfd3a91cfb5aa2e04aa77d7adfe96dcd9d7c3e0R993
