### ISSUE TITLE
Need to freeTemplate() when returning early.

### ISSUE THREAD

**Issue by dcoombs** [gamringer/php-pkcs11#3]
In a few places where parseTemplate() is used, freeTemplate() is only called at the bottom of the function, but if we return early due to a failure, we would leak the memory used by the template.

**Comment by dcoombs** [comment]
(Fixed in commit a9c6b08fa5369ff8a54cda6ee961801492edfe1f in my fork, but I don't know what would happen if I make a new PR before the last one is merged?)

**Comment by gamringer** [comment]
That commit is already added to the PR, no worries.
