### ISSUE TITLE
tests: PHP11_PIN vs PHP11_SOPIN

### ISSUE THREAD

**Issue by vjardin** [gamringer/php-pkcs11#30]
Guillaume,

The test uses SOPIN, but PHP11_PIN is checked from the env:
https://github.com/gamringer/php-pkcs11/blob/156902b58f25f0f534d8849afb2230bb7d3954be/tests/0108-login-so.phpt#L18

I could provide a pull request to fix it, but I'd like to check first if you are looking for something specific here ?

**Comment by gamringer** [comment]
That was just a mistake. I fixed it in c0c56d1573c414ac4bf317b5ff4e863b0f781eb5
