### ISSUE TITLE
Module variable going out of scope causes open session to be broken and cause SegFault

### ISSUE THREAD

**Issue by Magentron** [gamringer/php-pkcs11#51]
This is related to #31.

When doing something like this (pseudo code):

        // function loadModule($path): Module
        return new Module($path);
        
        // function openSession($path, $slot, $pin): Session
        $module = loadModule($path)
        $session = $module->openSession($slot, Pkcs11\CKF_RW_SESSION);
        $session->login(Pkcs11\CKU_USER, $pin);
        $session->getInfo(); // debug
        return $session;
                
        // function getObjects(Session $session)
        return $session->findObjects([
            Pkcs11\CKA_LABEL => 'My name',
        ]);

Before the `findObjects()` call, the C function `pkcs11_shutdown()` is called for the module and upon entering `findObjects()` the session `functionList` is *NULL*.

If I put the calls sequentially without functions it does work, so it seems that upon leaving `openSession()` somehow the PKCS11 shutdown function is called for the module because it going out of scope. This probably should not happen since the session is still open.

How can we solve this best?

**Comment by gamringer** [comment]
I remember having tested this specifically to avoid what you're describing. Obviously, whatever I did was wrong.

I'll look into it. Thanks.

**Comment by Magentron** [comment]
My first hunch would be that reference counting would be necessary.

**Comment by gamringer** [comment]
Yeah, that's what I'm thinking as well.

**Comment by Magentron** [comment]
Let me know if I can help

**Comment by vjardin** [comment]
@gamringer 

Few months ago, I wanted to introduce a constructor and destructor in order to benefit from PHP's internal ref counters. I feel it could help to solve such issue.
