### ISSUE TITLE
How to use in Laravel application?

### ISSUE THREAD

**Issue by Matt561** [gamringer/php-pkcs11#60]
Forgive my ignorance. My only experiences with php are using Laravel and Composer to install packages.

How would I use this library in a Laravel project? I don't understand how to pull this code in since it isn't accessible using a package manager.

Again I apologize for the lack of knowledge and appreciate any help provided!

Would love to use this in my Laravel app to communicate with a Thales LunaHSM. As far as I know, they've provided me with all necessary files to interact with one if their hsms. Just not sure how to use this library

**Comment by Magentron** [comment]
Hi @Matt561,

This is a PHP extension, you can read more about them here:
- https://www.zend.com/blog/php-development-using-php-extensions
- https://www.php.net/manual/en/extensions.php
- https://ma.ttias.be/how-to-compile-and-install-php-extensions-from-source/

**Comment by MattG561** [comment]
@Magentron Thanks for the insight!

For anyone in the same position, I got it working using pecl.

- Install `pecl`
- Install extension:`pecl install pkcs11`
- Add extension to php.ini: `echo "extension=pkcs11.so" > /path/to/php.ini`

**Comment by Matt561** [comment]
@Magentron 

I see that this library allows the generation of keypairs. Does it yet allow signing (ecdsa secp256k1) using those newly generated keys?

**Comment by gamringer** [comment]
Hi @Matt561 

If your HSM supports the curve by name, you should be able to use this extension to sign using secp256k1. Since you mentionned LunaHSM, I will guess that you are using the firmware version >= 7.3, which should support it.

Try this:

```php
$keypair = $session->generateKeyPair(new Pkcs11\Mechanism(Pkcs11\CKM_EC_KEY_PAIR_GEN), [
  Pkcs11\CKA_VERIFY => true,
  Pkcs11\CKA_LABEL => "Test ECDSA Public",
  Pkcs11\CKA_EC_PARAMS => hex2bin('06052B8104000A'),
],[
  Pkcs11\CKA_TOKEN => false,
  Pkcs11\CKA_PRIVATE => true,
  Pkcs11\CKA_SENSITIVE => true,
  Pkcs11\CKA_SIGN => true,
  Pkcs11\CKA_LABEL => "Test ECDSA Private",
]);

$pkey = $keypair->pkey;
$skey = $keypair->skey;

$data = "Hello World!";
$hash = hash('sha256', $data, true);
$mechanism = new Pkcs11\Mechanism(Pkcs11\CKM_ECDSA);
$signature = $skey->sign($mechanism, $hash);
$check = $keypair->pkey->verify($mechanism, $hash, $signature);

$session->logout();
```

Also, this library does not provide a dedicated parameters object for CKM_BIP32_*_DERIVE mechanisms, since they are proprietary to Thales, so you won't be able to use it for deriving HD wallet keys. That would be a good addition though.

**Comment by MattG561** [comment]
Awesome! Thank you!

I actually was having trouble using this library. When trying to open a new session I get the `CRK_TOKEN_NOT_PRESENT` error despite having one (other libs can successfully interact with the hsm). 

With this in mind, I tried to use the `initToken` function that is provided from this library but it actually crashed my docker container with a `segmentation fault` error.

**Comment by gamringer** [comment]
Hi @MattG561,

apologies for the late reply, I simply did not see the notification for your last message.

Which HSM model and firmware versions are you using ?

Also, how are you using the extension exactly ? Apache mod_php, FPM, CLI, other ?

**Comment by gamringer** [comment]
Closing, can reopen if more details are provided
