### ISSUE TITLE
Variable types of attributes are not compareable with constants

### ISSUE THREAD

**Issue by JanSlabon** [gamringer/php-pkcs11#63]
To be able to control an instance of `\Pkcs11\Key` we need to get some attributes from it:

```
$attributes = $privateKey->getAttributeValue([
    \Pkcs11\CKA_PRIVATE, 
    \Pkcs11\CKA_SIGN, 
    \Pkcs11\CKA_KEY_TYPE
]);
```

All of these values are raw bytestrings and it is impossible to compare them with the existing constants. E.g.:

```
if ($attributes[\Pkcs11\CKA_KEY_TYPE] === \Pkcs11\CKK_RSA) {
   ...
}
```
But as the attributes are strings this does not work. Is this an intended behavior or are we missing something?

It is possible to use integer or boolean values when e.g. creating key pairs using the same key constants:

```
$keypair = $session->generateKeyPair(new Pkcs11\Mechanism(Pkcs11\CKM_RSA_PKCS_KEY_PAIR_GEN), [
	Pkcs11\CKA_VERIFY => true,
	Pkcs11\CKA_MODULUS_BITS => 2048,
	Pkcs11\CKA_PUBLIC_EXPONENT => hex2bin('010001'),
	Pkcs11\CKA_LABEL => "Test RSA Public",
],[
	Pkcs11\CKA_TOKEN => false,
	Pkcs11\CKA_PRIVATE => true,
	Pkcs11\CKA_SENSITIVE => true,
	Pkcs11\CKA_SIGN => true,
	Pkcs11\CKA_LABEL => "Test RSA Private",
]);
```

Wouldn't it be correct, if these values are also boolean and/or integer values, when they are received back?

If this is an internal issue of how PKCS11 works under the hood, can you share some best practice how to compare these values?

Would this be a correct comparison:

```
if ($attributes[\Pkcs11\CKA_KEY_TYPE] === pack("P", \Pkcs11\CKK_RSA)) {
   ...
}
```

?

Thanks!

**Comment by gamringer** [comment]
You're correct. When I coded it, I wanted to use native PHP types where it made sense, but I overlooked the fact that when retrieving from the underlying P11 module, everything would be strings. I'll make the adjustments.
