### ISSUE TITLE
How To Use On Windows ?

### ISSUE THREAD

**Issue by Heba10** [gamringer/php-pkcs11#64]

**Comment by vjardin** [comment]
Try to compile with some few ifdef. Most of the APIs are following the OASIS/scard semantic which is valid for Windows too.

**Comment by gamringer** [comment]
Hi @Heba10

I did not code this extension with Windows in mind, or tested it for it.

As @vjardin suggested, it may work with a few tweaks. If you get it to work, so submit a patch, I'll merge it in.
