### ISSUE TITLE
AWS Cloud HSM Support

### ISSUE THREAD

**Issue by elabuwa** [gamringer/php-pkcs11#71]
Hi team,

Sorry noob in the cryptography area and the whole HSM scenario.
I was just wondering if AWS Cloud HSM is supported.

Thanks

**Comment by vjardinMisc** [comment]
Of you find any pkcs11 Linux driver from AWS, yes it'll work since this PHP module is generic enough.

Try 
wget https://s3.amazonaws.com/cloudhsmv2-software/CloudHsmClient/Focal/cloudhsm-pkcs11_latest_u20.04_amd64.deb
for Instance.

**Comment by elabuwa** [comment]
Thank you @vjardinMisc. Will give it a go.
